package com.readysteady.geolocation;

import java.io.Serializable;
import java.util.List;

import org.apache.commons.lang.builder.ToStringBuilder;

import com.fasterxml.jackson.annotation.JsonProperty;


/**
 * Autogenerated by APIOMatic.
 * 
 */
public class GeolocationResult
    implements Serializable
{

 
    @JsonProperty("address_components")
    private List<GeolocationAddress> addressComponents;

    @JsonProperty("formatted_address")
    private String formattedAddress;
  
    private GeolocationGeometry geometry;
  
    private String partial_match;
    private List<String> types;
    private final static long serialVersionUID = 7133553622959686501L;

    public GeolocationResult() {
    }

    public List<GeolocationAddress> getAddressComponents() {
        return addressComponents;
    }

    public void setAddressComponents(final List<GeolocationAddress> someAddressComponents) {
        this.addressComponents = someAddressComponents;
    }

    public String getFormattedAddress() {
        return formattedAddress;
    }

    public void setFormattedAddress(final String aFormattedAddress) {
        this.formattedAddress = aFormattedAddress;
    }

    public GeolocationGeometry getGeometry() {
        return geometry;
    }

    public void setGeometry(final GeolocationGeometry aGeometry) {
        this.geometry = aGeometry;
    }

    public List<String> getTypes() {
        return types;
    }

    public void setTypes(final List<String> someTypes) {
        this.types = someTypes;
    }

    @Override
    public String toString() {
        return new ToStringBuilder(this.getClass()).append("addressComponents", addressComponents).append("formattedAddress", formattedAddress).append("geometry", geometry).append("types", types).toString();
    }

	public String getPartial_match() {
		return partial_match;
	}

	public void setPartial_match(String partial_match) {
		this.partial_match = partial_match;
	}

}
