package com.readysteady.geolocation;

import java.io.Serializable;
import javax.persistence.OneToOne;
import com.fasterxml.jackson.annotation.JsonProperty;
import org.apache.commons.lang.builder.ToStringBuilder;


/**
 * Autogenerated by APIOMatic.
 * 
 */
public class GeolocationGeometry
    implements Serializable
{

    @OneToOne
    private GeolocationGeometryLocation location;
    @OneToOne
    @JsonProperty("location_type")
    private String locationType;
    @OneToOne
    private GeolocationGeometryViewport viewport;
    private final static long serialVersionUID = 5974174501536527282L;

    public GeolocationGeometry() {
    }

    public GeolocationGeometryLocation getLocation() {
        return location;
    }

    public void setLocation(final GeolocationGeometryLocation aLocation) {
        this.location = aLocation;
    }

    public String getLocationType() {
        return locationType;
    }

    public void setLocationType(final String aLocationType) {
        this.locationType = aLocationType;
    }

    public GeolocationGeometryViewport getViewport() {
        return viewport;
    }

    public void setViewport(final GeolocationGeometryViewport aViewport) {
        this.viewport = aViewport;
    }

    @Override
    public String toString() {
        return new ToStringBuilder(this.getClass()).append("location", location).append("locationType", locationType).append("viewport", viewport).toString();
    }

}
