package com.readysteady.geolocation;

import java.io.Serializable;
import javax.persistence.OneToOne;
import org.apache.commons.lang.builder.ToStringBuilder;


/**
 * Autogenerated by APIOMatic.
 * 
 */
public class GeolocationGeometryViewport
    implements Serializable
{

    @OneToOne
    private GeolocationGeometryViewportNortheast northeast;
    @OneToOne
    private GeolocationGeometryViewportSouthwest southwest;
    private final static long serialVersionUID = 4198725269821973589L;

    public GeolocationGeometryViewport() {
    }

    public GeolocationGeometryViewportNortheast getNortheast() {
        return northeast;
    }

    public void setNortheast(final GeolocationGeometryViewportNortheast aNortheast) {
        this.northeast = aNortheast;
    }

    public GeolocationGeometryViewportSouthwest getSouthwest() {
        return southwest;
    }

    public void setSouthwest(final GeolocationGeometryViewportSouthwest aSouthwest) {
        this.southwest = aSouthwest;
    }

    @Override
    public String toString() {
        return new ToStringBuilder(this.getClass()).append("northeast", northeast).append("southwest", southwest).toString();
    }

}
